### PR TITLE
Added contributors from Hack4Missions Prezi presentation

### PR DESCRIPTION
**Pull request by tjohnson314**

### CODE REVIEW

**Comment by tjohnson314** [comment]
Fixes #31

**Comment by heyitscoco** [comment]
It looks like for some reason we're logging the entire tokenized text to Travis, which is breaking the build
screen shot 2016-01-09 at 10 15 55 am

**Comment by bbriggs** [comment]
I'm going to merge this one because it's a trivial file, but before we do any other PRs, we need to get the Travis tests working again.

**Comment by bbriggs** [comment]
Closes #31

**Pull request merged**
